model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: generator.src.modules.diffusion.latent.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    unet_config:
      target: generator.src.model.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: embedder.src.model.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 1
    # train:
    #   target: generator.src.dataloader.CustomTrain
    #   params:
    #     training_images_list_file: /home/ubuntu/scania-raw-diff/src/generator/logs/optim/uncond/sets/train.txt
    #     degradation: cv_bilinear
    #     downscale_f: 4
    #     size: 256
    validation:
      target: generator.src.dataloader.CustomVal
      params:
        validation_images_list_file: /mnt/efs/fs1/smartphone-image-denoising-dataset/cycleisp-val.txt
        degradation: cv_bilinear
        downscale_f: 4
        size: 256
    # test:
    #   target: generator.src.dataloader.CustomTest
    #   params:
    #     test_images_list_file: /home/ubuntu/scania-raw-diff/src/generator/logs/optim/uncond/sets/val.txt
    #     degradation: cv_bilinear
    #     downscale_f: 4
    #     size: 256