model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 8
    train:
      target: embedder.src.dataloader.CustomTrain
      params:
        training_images_list_file: /home/ubuntu/scania-raw-diff/src/embedder/logs/optim/rgb-rgb/sets/train.txt
        size: 256
    validation:
      target: embedder.src.dataloader.CustomVal
      params:
        validation_images_list_file: /home/ubuntu/scania-raw-diff/src/embedder/logs/optim/rgb-rgb/sets/val.txt
        size: 256
    test:
      target: embedder.src.dataloader.CustomTest
      params:
        test_images_list_file: /home/ubuntu/scania-raw-diff/src/embedder/logs/optim/rgb-rgb/sets/test.txt
        size: 256

# lightning:
#   trainer:
#     benchmark: True
#     accumulate_grad_batches: 2