model: # Working with z of shape (1, 3, 64, 64) = 12288 dimensions
  base_learning_rate: 4.5e-06
  target: embedder.src.model.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target:  embedder.src.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

  
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: embedder.src.dataloader.CustomTrain
      params:
        training_images_list_file: /mnt/efs/fs1/campipe-road-data/train.txt
        size: 256
    validation:
      target: embedder.src.dataloader.CustomVal
      params:
        validation_images_list_file: /mnt/efs/fs1/campipe-road-data/val.txt
        size: 256
    # test:
    #   target: embedder.src.dataloader.CustomTest
    #   params:
    #     test_images_list_file: /home/ubuntu/scania-raw-diff/src/embedder/logs/optim/rgb-rgb/sets/test.txt
    #     size: 512